create PDP fragment
tolia-ogurt/trempel pull request #1
Opened 2021-11-22 14:22 UTC by tolia-ogurt

2021-11-23 11:32 UTC, DaryaErofeeva requested changes

2021-11-23 11:32 UTC, DaryaErofeeva commented on .gitignore
> -*.apk
Move these changes to Initial commit on master

2021-11-23 11:32 UTC, DaryaErofeeva commented on app/.gitignore
> +/build
We should have only one `.gitignore` for the whole project

2021-11-23 11:32 UTC, DaryaErofeeva commented on app/build.gradle
> +        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
Have you already added any tests?

2021-11-23 11:32 UTC, DaryaErofeeva commented on app/build.gradle
> +    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'
I don't think we need these test dependencies for now, please remove them

2021-11-23 11:32 UTC, DaryaErofeeva commented on app/src/androidTest/java/com/example/trempel/ExampleInstrumentedTest.kt
> +}
Let's remove this automatically generated test class

2021-11-23 11:32 UTC, DaryaErofeeva commented on app/build.gradle
> +            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
I think we can get rid of proguard now

2021-11-23 11:32 UTC, DaryaErofeeva commented on app/proguard-rules.pro
> +# Add project specific ProGuard rules here.
I think we can get rid of proguard now, for now this's just the file bunch of comments

2021-11-23 11:32 UTC, DaryaErofeeva commented on app/src/main/java/com/example/trempel/PdpFragment.kt
> +class PdpFragment:Fragment(R.layout.pdp_fragment) {
Please, follow the formatting convention suggested by JetBrains https://kotlinlang.org/docs/coding-conventions.html#colon
`Always put a space after :.`

_You can use `Command + Alt + L` and it'll do some formatting magic for you_

2021-11-23 11:32 UTC, DaryaErofeeva commented on app/src/test/java/com/example/trempel/ExampleUnitTest.kt
> +}
Let's remove this automatically generated test class

2021-11-23 11:32 UTC, DaryaErofeeva commented on app/src/main/res/layout/activity_main.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
Do we actually need ConstraintLayout as a wrapper in this case?

2021-11-23 11:32 UTC, DaryaErofeeva commented on app/src/main/res/layout/pdp_fragment.xml
> +        android:id="@+id/cardView"
why do we have `@+id/cardView` value for id?

2021-11-23 11:32 UTC, DaryaErofeeva commented on app/src/main/res/layout/pdp_fragment.xml
> +        android:id="@+id/btnAddToCart"
You have 3 naming approaches in this file:
* `iV_product` - abbreviation of view type  + `_` + `product`
* `productTitle `, `productPrice`, `productDescription` etc. - `product` + content type
* `btnAddToCart` - abbreviation of view type + view text

Let's stick to one of them, I'd suggest `abbreviation + content type` (e.g. `iv_product_image`, `tv_product_title` etc.) but feel free to apply other option as the main goal is naming consistency

2021-11-23 11:32 UTC, DaryaErofeeva commented on app/src/main/res/layout/pdp_fragment.xml
> +        android:layout_height="56dp"
Should be extracted as dimention

2021-11-23 11:32 UTC, DaryaErofeeva commented on app/src/main/res/values-night/themes.xml
> +    <style name="Theme.Trempel" parent="Theme.MaterialComponents.DayNight.DarkActionBar">
The additional task will be created for changing the theme colors

2021-11-23 11:32 UTC, DaryaErofeeva commented on app/src/main/res/values/strings.xml
> +        >"Slim-fitting style, contrast raglan long sleeve, three-button henley placket, light weight soft fabric for breathable and comfortable wearing. \nAnd Solid stitched shirts with round neck ma
Something happened to the formatting

2021-11-23 11:32 UTC, DaryaErofeeva commented on app/src/main/res/values/themes.xml
> +<resources xmlns:tools="http://schemas.android.com/tools">
I don't think we should have light and dark theme

2021-11-23 11:32 UTC, DaryaErofeeva commented on app/src/main/java/com/example/trempel/PdpFragment.kt
> +}
I don't think we need class body here

2021-11-23 11:32 UTC, DaryaErofeeva commented on app/src/main/res/layout/pdp_fragment.xml
> +        android:textSize="18sp"
textSizes should also be extracted from the layout file

2021-11-23 11:32 UTC, DaryaErofeeva commented on app/src/main/res/layout/pdp_fragment.xml
> +        android:textSize="24sp"
textSizes should also be extracted from the layout file

2021-11-23 11:32 UTC, DaryaErofeeva commented on app/src/main/res/layout/pdp_fragment.xml
> +        android:id="@+id/productTitle"
Looks like you haven't defined the lineHeight

2021-11-23 11:32 UTC, DaryaErofeeva commented on app/src/main/res/layout/pdp_fragment.xml
> +        android:id="@+id/productPrice"
Looks like you haven't defined the lineHeight

2021-11-23 11:32 UTC, DaryaErofeeva commented on app/src/main/res/layout/pdp_fragment.xml
> +        android:layout_height="272dp"
This value should also be extracted to dimentions

2021-11-23 15:24 UTC, tolia-ogurt commented on .gitignore
> -*.apk
ok

2021-11-25 14:44 UTC, DaryaErofeeva approved these changes

2021-11-25 14:46 UTC, merged